spring.application.name=TrabalhoDenis

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=PostgreSQL

# Faz o Spring criar/atualizar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL gerado no console
spring.jpa.show-sql=true